---
- name: Update Dynamic Inventory
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    inventory_data: "{{ api_inventory_data | default({}) }}"

  tasks:
    - name: Display inventory data
      debug:
        var: inventory_data

    - name: Trigger inventory update
      ansible.controller.inventory_source_update:
        name: "Remedy API Source"
        inventory: "Dynamic Inventory from Remedy"
        organization: "Default"  # Replace with your organization name if different
        source_vars:
          INVENTORY_DATA: "{{ inventory_data | to_json }}"
      register: inventory_update_result

    - name: Wait for inventory update
      ansible.controller.job_wait:
        job_id: "{{ inventory_update_result.id }}"
      register: wait_result

    - name: Display updated inventory
      debug:
        var: groups
