---
- name: Update Dynamic Inventory
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    inventory_data: "{{ api_inventory_data | default({}) }}"

  tasks:
    - name: Set inventory data as an environment variable
      set_fact:
        inventory_env: "INVENTORY_DATA='{{ inventory_data | to_json }}'"

    - name: Trigger inventory update
      ansible.controller.inventory_source_update:
        name: "Remedy API Source"
        inventory: "Dynamic Inventory from Remedy"
        organization: "Default"  # Replace with your organization name if different
      environment: "{{ inventory_env }}"
      register: inventory_update_result

    - name: Wait for inventory update
      ansible.controller.job_wait:
        job_id: "{{ inventory_update_result.id }}"
      register: wait_result

    - name: Display updated inventory
      debug:
        var: groups
